---
server:
    packages: [vim, git, imagemagick, sendmail, drush, unzip, zip, g++, libssl-dev, apache2-utils]
    timezone: UTC
    locale: en_US.UTF-8

    # Password is "vagrant". Created with:
    # python -c 'import crypt; print crypt.crypt("vagrant", "$1$SomeSalt$")'
    root_pwd: $1$Blabla$M90f9fY/FtNYwP/1I8gGL0

vagrant_local:
    vm: { hostname: default }

nginx:
    servername: default
    docroot: /var/www/html

php:
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-imagick, php5-curl, php5-gd, php5-mysql]
    memory_limit: 1024M
    timeout: 300


mariadb:
    root_password: ''
    database: db

composer:

terminus:
    version: '0.11.2'

xdebug:



#redis:
#    install: '1'
#    port: '6379'

#solr:
#    install: '1'
#    port: '8983'
#    version: 5.2.0
#    cloud_mode: '0'




