---

- name: Replace php.ini file for php-fpm
  sudo: yes
  template: src=php-fpm.ini.tpl dest=/etc/php5/fpm/php.ini
  notify: restart php5-fpm

- name: Replace www.conf file for php-fpm
  sudo: yes
  template: src=php-fpm.www.conf.tpl dest=/etc/php5/fpm/pool.d/www.conf
  notify: restart php5-fpm
