---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Prepare folder for logs
  sudo: yes
  file: path=/var/www/logs state=directory mode=0775

- name: Change default nginx site
  sudo: yes
  template: src=default.tpl dest=/etc/nginx/sites-available/default

- name: Change the main nginx config
  sudo: yes
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf

- name: Delete default index.html file
  file: path=/var/www/html/index.html state=absent

- name: Restart nginx
  service: name=nginx state=restarted
