---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Prepare folder for logs
  sudo: yes
  file: path=/var/www/logs state=directory mode=0775

- name: Change default nginx site
  sudo: yes
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Change the main nginx config
  sudo: yes
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf
  notify: restart nginx
