- name: Create a new folder for Terminus
  file: path=/var/terminus state=directory mode=0775

- name: Install Pantheon Terminus
  composer:
    command: "require"
    arguments: "pantheon-systems/terminus:{{ terminus.version }}"
    working_dir: "/var/terminus"

- name: Make Pantheon Terminus accessible from command line
  file:
    src: /var/terminus/vendor/bin/terminus
    dest: /usr/local/bin/terminus
    state: link
