---
- name: Install xDebug
  sudo: yes
  apt: pkg=php5-xdebug state=latest

- name: Copy xdebug ini into main extension config folder.
  template:
    src: xdebug.ini.j2
    dest: "/etc/php5/mods-available/xdebug.ini"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php5-fpm
